### ISSUE TITLE
empty string inserted instead of NULL for binary values

### ISSUE THREAD

**Issue by ysth** [gooddata/DBD-MariaDB#118]
The following code stores a 0-length string instead of NULL as expected:
```
$dbh->do("drop table if exists bar");
$dbh->do("create table bar (foo blob)");
my $sth = $dbh->prepare("insert into bar (foo) values (?)");
my $value = undef;
$sth->bind_param(1, $value, DBI::SQL_BINARY);
$sth->execute();
```

**Comment by ysth** [comment]
This may be an issue with my DBI subclass; closing for now

**Comment by pali** [comment]
Hi! I tested your code sample with last DBD::MariaDB and it stores NULL into database. There is no empty string.
