### ISSUE TITLE
README.pod included in distribution

### ISSUE THREAD

**Issue by Grinnz** [gooddata/DBD-MariaDB#146]
README.pod is included in the root of the distribution. This is discouraged (and a warning is produced under newer EUMM) because EUMM will install any .pm and .pod files from the root -- this one will end up at DBD/README.pod which is an unhelpful location and a namespace not owned by this distribution. It should be excluded from the distribution, only plaintext or .md READMEs should be shipped in the root.

**Comment by pali** [comment]
Hello! In pull request https://github.com/gooddata/DBD-MariaDB/pull/148 is a fix for this problem. README.pod will be now installed as lib/DBD/MariaDB/README.pod file. Similarly autogenerated manpage.

README.pod in top level directory on github is a starting point and provides details about project. Bugs in ExtUtils::MakeMakers should not be reason to stop providing useful files.

**Comment by pali** [comment]
Could you please check that pull request if it fixes that problem?

**Comment by pali** [comment]
Is there any problem to have README file also in distribution on CPAN? I guess that downstream packagers for different Linux distribution would like to see some simple README file in released tarball.

Storing README file in different directory (like lib/DBD/MariaDB as you suggested) would not work. All software store README file in released tarball in top level directory. Nobody would be trying to find main README file deeply in some third level subdirectory.

**Comment by tupinek** [comment]
@pali Note: There is README file in my distributions. But in form of text, not POD. I think you can add creating of README from README.pod and README.pod skip in distribution.

**Comment by pali** [comment]
> Yes, README.pod specifically is subject to the ExtUtils::MakeMaker bug and cannot be included at the top level.

It should not be affected after applying https://github.com/gooddata/DBD-MariaDB/pull/148 change.

**Comment by pali** [comment]
It is top level README file like in any other software distributed in tarball and visible by as main page on github. Therefore it cannot be in subdirectory and cannot be in MANIFEST.SKIP (as it would not be included in release tarball).

**Comment by choroba** [comment]
I think the current solution is acceptable, if maybe not standard. It's unfortunate that we can't specify "use the general rules, but handle these particular files differently" - currently, one either uses the general rules, or has to specify the install location for each file manually.
