### ISSUE TITLE
Some problems with Unicode encoding

### ISSUE THREAD

**Issue by illuusio** [gooddata/DBD-MariaDB#152]
As I have read Unicode explanation multiple times and code works with old MySQL driver (which Unicode support is considered borked there I just enable utf8 support and everything works). With MariaDB example char 'ö' converts for chars: Ã¶. This same issue can be achieved with Perl JSON-module when you enable UTF8 mode and they already are UTF8 so they are blindly converted second time.
Main problem is that when one haves string like with UTF-8 char 'ö' it still converts them to Unicode second time (Ã¶).

**Comment by pali** [comment]
Please provide code example which can be used to reproduce your issue. Thanks!

**Comment by illuusio** [comment]
Sorry this was my bad. MariaDB driver actually works as expected (and promised) and there was several old mysql driver haxxx (Which I wasn't aware of). Still in 2019 (soon 2020) Unicode is problem. Sorry for noise and thank you for better working driver.
