### ISSUE TITLE
utf8mb4 problems

### ISSUE THREAD

**Issue by Gazoo** [gooddata/DBD-MariaDB#159]
There seem to be some utf8mb4 encoding problems with the DBD-MariaDB driver. I confirmed that the data is scrambled in the database so this isn't a display problem.

The DB schema column is created with:
`subject varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '',`

Switching over to the perl-DBD-MySQL driver fixes the issue. This is a Centos 8 server with perl 5, version 26, subversion 3 (v5.26.3)

![2020-08-28_01h25_05](https://user-images.githubusercontent.com/379016/91533573-56c65680-e8cd-11ea-8ab6-50c5db3fd387.png)

**Comment by Grinnz** [comment]
It is more likely the data is being inserted incorrectly, and that DBD::mysql's bugs are resulting in correct output. [Freenode IRC](https://webchat.freenode.net/#perl) could assist in debugging if you are able to show the code involved.

**Comment by Gazoo** [comment]
@Grinnz the code is just the standard Amavis 2.12 package from Centos 8.

**Comment by Grinnz** [comment]
Yes this is absolutely broken. None of that broken UTF-8 conversion should be done when using DBD::MariaDB, it is probably to work around DBD::mysql's bugs.

**Comment by Grinnz** [comment]
Instead of converting to octets, if you run "utf8::upgrade $chars" that should ensure that character string is interpreted correctly by both drivers.

**Comment by Gazoo** [comment]
OK thanks @Grinnz . I'll file a bug with Amavis and switch over using a patched DBD::mysql (to work around a data type bug) as it will probably take some time to support the DBD::MariaDB driver in Amavis (I thought that it would be an easy switch over between the two drivers but I guess not).
